const mockProducts = [
	{
		id: "p1",
		name: "Premium Industrial Packaging Cartons",
		price: 45,
		vendorName: "Apex Traders",
		vendorId: "v_12345",
		location: "Ahmedabad, GJ",
		supplySignal: "High supply",
		verified: true,
		moq: "500 units",
		specs: "3-ply corrugated",
		bulkPrice: 42,
		bulkQuantity: 1000,
		category: "Packaging",
		image: "https://placehold.co/400x300/e2e8f0/1e293b?text=Packaging+Cartons",
	},
	{
		id: "p2",
		name: "Heavy-Duty Shipping Pallets",
		price: 280,
		vendorName: "Bharat Woodworks",
		vendorId: "v_23456",
		location: "Ludhiana, PB",
		supplySignal: "Low stock",
		verified: true,
		moq: "50 units",
		specs: "ISPM 15 certified pine",
		bulkPrice: 265,
		bulkQuantity: 200,
		category: "Packaging",
		image: "https://placehold.co/400x300/d1d5db/1f2937?text=Pallets",
	},
	{
		id: "p3",
		name: '4K USB-C Monitor 27"',
		price: 12500,
		vendorName: "TechVision Distributors",
		vendorId: "v_34567",
		location: "Bengaluru, KA",
		supplySignal: "In stock",
		verified: true,
		moq: "10 units",
		specs: "IPS, 60Hz, 5ms",
		bulkPrice: 11900,
		bulkQuantity: 50,
		category: "Electronics",
		image: "https://placehold.co/400x300/bfdbfe/1e40af?text=Monitor",
	},
	{
		id: "p4",
		name: "Lithium-Ion Battery Pack 48V 20Ah",
		price: 6750,
		vendorName: "EnerGen Solutions",
		vendorId: "v_45678",
		location: "Pune, MH",
		supplySignal: "High supply",
		verified: false,
		moq: "25 units",
		specs: "NMC chemistry, BMS included",
		bulkPrice: 6400,
		bulkQuantity: 100,
		category: "Electronics",
		image: "https://placehold.co/400x300/fef08a/854d0e?text=Battery+Pack",
	},
	{
		id: "p5",
		name: "Industrial Grade Copper Wire (10 AWG)",
		price: 890,
		vendorName: "MetalEx India",
		vendorId: "v_56789",
		location: "Mumbai, MH",
		supplySignal: "Moderate",
		verified: true,
		moq: "200 meters",
		specs: "99.9% pure, bare copper",
		bulkPrice: 845,
		bulkQuantity: 1000,
		category: "Raw Materials",
		image: "https://placehold.co/400x300/fcd34d/92400e?text=Copper+Wire",
	},
	{
		id: "p6",
		name: "Polypropylene Granules (PP)",
		price: 92,
		vendorName: "PlastWorld Corp",
		vendorId: "v_67890",
		location: "Vadodara, GJ",
		supplySignal: "High supply",
		verified: true,
		moq: "500 kg",
		specs: "Injection molding grade",
		bulkPrice: 87,
		bulkQuantity: 2000,
		category: "Raw Materials",
		image: "https://placehold.co/400x300/c7d2fe/4338ca?text=PP+Granules",
	},
	{
		id: "p7",
		name: "Stainless Steel Hex Bolts M12 x 50mm",
		price: 6.5,
		vendorName: "Precision Fasteners",
		vendorId: "v_78901",
		location: "Coimbatore, TN",
		supplySignal: "In stock",
		verified: true,
		moq: "1000 pieces",
		specs: "A2-70, DIN 933",
		bulkPrice: 5.8,
		bulkQuantity: 5000,
		category: "Hardware",
		image: "https://placehold.co/400x300/e5e7eb/374151?text=Hex+Bolts",
	},
	{
		id: "p8",
		name: "Ball Bearings 6205-2RS",
		price: 145,
		vendorName: "SKF Bearing House",
		vendorId: "v_89012",
		location: "Delhi, DL",
		supplySignal: "Low stock",
		verified: true,
		moq: "250 pieces",
		specs: "Double sealed, chrome steel",
		bulkPrice: 132,
		bulkQuantity: 1000,
		category: "Hardware",
		image: "https://placehold.co/400x300/d1d5db/111827?text=Bearings",
	},
	{
		id: "p9",
		name: "Organic Cotton Yarn (Ne 30/1)",
		price: 340,
		vendorName: "GreenThread Textiles",
		vendorId: "v_90123",
		location: "Tiruppur, TN",
		supplySignal: "High supply",
		verified: false,
		moq: "150 kg",
		specs: "Combed, ring-spun, GOTS certified",
		bulkPrice: 315,
		bulkQuantity: 500,
		category: "Textiles",
		image: "https://placehold.co/400x300/f3f4f6/374151?text=Cotton+Yarn",
	},
	{
		id: "p10",
		name: "Sulphuric Acid 98% (Industrial)",
		price: 18.5,
		vendorName: "ChemCore Industries",
		vendorId: "v_01234",
		location: "Vapi, GJ",
		supplySignal: "Moderate",
		verified: true,
		moq: "1000 litres",
		specs: "Technical grade, tanker load",
		bulkPrice: 17.2,
		bulkQuantity: 5000,
		category: "Chemicals",
		image: "https://placehold.co/400x300/fecaca/991b1b?text=Sulphuric+Acid",
	},
];

export default mockProducts;
