const mockProducts = [
  {
    id: "p1",
    name: "Premium Industrial Packaging Cartons",
    category: "Packaging",
    image: "https://placehold.co/400x300/e2e8f0/1e293b?text=Packaging+Cartons",
    description: "Durable corrugated cartons for bulk shipping and storage.",
    suppliers: [
      {
        id: "s1-101",
        name: "Apex Traders",
        image: "https://placehold.co/300x300/e2e8f0/1e293b?text=Apex+Traders",
        verified: true,
        rating: 4.8,
        reviews: 421,
        price: 45,
        discountPrice: 42,
        moq: 500,
        stock: 860,
        shippingDays: 5,
        country: "India",
        city: "Ahmedabad",
        responseRate: "98%",
        responseTime: "Within 1 hour",
        gstVerified: true,
        trustScore: "87%",
        yearsInBusiness: 12,
        completedOrders: 920,
        totalProducts: 310,
        mobile: "+91 98765 10101",
      },
      {
        id: "s1-102",
        name: "Bharat Packs",
        image: "https://placehold.co/300x300/e2e8f0/1e293b?text=Bharat+Packs",
        verified: true,
        rating: 4.5,
        reviews: 312,
        price: 43,
        discountPrice: 40,
        moq: 600,
        stock: 540,
        shippingDays: 6,
        country: "India",
        city: "Mumbai",
        responseRate: "95%",
        responseTime: "Within 2 hours",
        gstVerified: true,
        trustScore: "83%",
        yearsInBusiness: 9,
        completedOrders: 780,
        totalProducts: 240,
        mobile: "+91 98765 10102",
      },
      {
        id: "s1-103",
        name: "PackPro Solutions",
        image:
          "https://placehold.co/300x300/e2e8f0/1e293b?text=PackPro+Solutions",
        verified: true,
        rating: 4.9,
        reviews: 520,
        price: 47,
        discountPrice: 44,
        moq: 400,
        stock: 720,
        shippingDays: 4,
        country: "India",
        city: "Delhi",
        responseRate: "99%",
        responseTime: "30 minutes",
        gstVerified: true,
        trustScore: "91%",
        yearsInBusiness: 15,
        completedOrders: 1160,
        totalProducts: 430,
        mobile: "+91 98765 10103",
      },
    ],
  },
  {
    id: "p2",
    name: "Heavy-Duty Shipping Pallets",
    category: "Packaging",
    image: "https://placehold.co/400x300/d1d5db/1f2937?text=Pallets",
    description:
      "Robust wooden pallets suitable for warehouse and container logistics.",
    suppliers: [
      {
        id: "s2-201",
        name: "Bharat Woodworks",
        image:
          "https://placehold.co/300x300/d1d5db/1f2937?text=Bharat+Woodworks",
        verified: true,
        rating: 4.6,
        reviews: 315,
        price: 280,
        discountPrice: 265,
        moq: 50,
        stock: 120,
        shippingDays: 6,
        country: "India",
        city: "Ludhiana",
        responseRate: "96%",
        responseTime: "Within 1 hour",
        gstVerified: true,
        trustScore: "84%",
        yearsInBusiness: 10,
        completedOrders: 610,
        totalProducts: 180,
        mobile: "+91 98765 20201",
      },
      {
        id: "s2-202",
        name: "LogiPal Solutions",
        image:
          "https://placehold.co/300x300/d1d5db/1f2937?text=LogiPal+Solutions",
        verified: false,
        rating: 4.3,
        reviews: 198,
        price: 275,
        discountPrice: 260,
        moq: 80,
        stock: 210,
        shippingDays: 8,
        country: "India",
        city: "Jaipur",
        responseRate: "90%",
        responseTime: "Within 3 hours",
        gstVerified: false,
        trustScore: "79%",
        yearsInBusiness: 7,
        completedOrders: 420,
        totalProducts: 90,
        mobile: "+91 98765 20202",
      },
      {
        id: "s2-203",
        name: "PalletHub",
        image: "https://placehold.co/300x300/d1d5db/1f2937?text=PalletHub",
        verified: true,
        rating: 4.7,
        reviews: 402,
        price: 290,
        discountPrice: 278,
        moq: 40,
        stock: 180,
        shippingDays: 5,
        country: "India",
        city: "Pune",
        responseRate: "97%",
        responseTime: "Within 2 hours",
        gstVerified: true,
        trustScore: "88%",
        yearsInBusiness: 11,
        completedOrders: 830,
        totalProducts: 220,
        mobile: "+91 98765 20203",
      },
    ],
  },
  {
    id: "p3",
    name: '4K USB-C Monitor 27"',
    category: "Electronics",
    image: "https://placehold.co/400x300/bfdbfe/1e40af?text=Monitor",
    description:
      "Crystal-clear 4K USB-C monitor designed for business workstations and control rooms.",
    suppliers: [
      {
        id: "s3-301",
        name: "TechVision Distributors",
        image: "https://placehold.co/300x300/bfdbfe/1e40af?text=TechVision",
        verified: true,
        rating: 4.8,
        reviews: 520,
        price: 12500,
        discountPrice: 11900,
        moq: 10,
        stock: 58,
        shippingDays: 4,
        country: "India",
        city: "Bengaluru",
        responseRate: "98%",
        responseTime: "Within 1 hour",
        gstVerified: true,
        trustScore: "90%",
        yearsInBusiness: 14,
        completedOrders: 940,
        totalProducts: 620,
        mobile: "+91 98765 30301",
      },
      {
        id: "s3-302",
        name: "ScreenSource",
        image: "https://placehold.co/300x300/bfdbfe/1e40af?text=ScreenSource",
        verified: true,
        rating: 4.6,
        reviews: 342,
        price: 12350,
        discountPrice: 11850,
        moq: 15,
        stock: 72,
        shippingDays: 5,
        country: "India",
        city: "Mumbai",
        responseRate: "96%",
        responseTime: "Within 90 minutes",
        gstVerified: true,
        trustScore: "86%",
        yearsInBusiness: 9,
        completedOrders: 610,
        totalProducts: 330,
        mobile: "+91 98765 30302",
      },
      {
        id: "s3-303",
        name: "DisplayCrafters",
        image:
          "https://placehold.co/300x300/bfdbfe/1e40af?text=DisplayCrafters",
        verified: false,
        rating: 4.4,
        reviews: 210,
        price: 12200,
        discountPrice: 11700,
        moq: 20,
        stock: 40,
        shippingDays: 3,
        country: "India",
        city: "Delhi",
        responseRate: "92%",
        responseTime: "Within 2 hours",
        gstVerified: false,
        trustScore: "80%",
        yearsInBusiness: 8,
        completedOrders: 350,
        totalProducts: 200,
        mobile: "+91 98765 30303",
      },
    ],
  },
  {
    id: "p4",
    name: "Lithium-Ion Battery Pack 48V 20Ah",
    category: "Electronics",
    image: "https://placehold.co/400x300/fef08a/854d0e?text=Battery+Pack",
    description:
      "Reliable battery pack with integrated BMS for industrial power backups.",
    suppliers: [
      {
        id: "s4-401",
        name: "EnerGen Solutions",
        image: "https://placehold.co/300x300/fef08a/854d0e?text=EnerGen",
        verified: false,
        rating: 4.2,
        reviews: 92,
        price: 6750,
        discountPrice: 6400,
        moq: 25,
        stock: 210,
        shippingDays: 5,
        country: "India",
        city: "Pune",
        responseRate: "91%",
        responseTime: "Within 2 hours",
        gstVerified: true,
        trustScore: "79%",
        yearsInBusiness: 10,
        completedOrders: 510,
        totalProducts: 150,
        mobile: "+91 98765 40401",
      },
      {
        id: "s4-402",
        name: "PowerCore Traders",
        image: "https://placehold.co/300x300/fef08a/854d0e?text=PowerCore",
        verified: true,
        rating: 4.6,
        reviews: 210,
        price: 6900,
        discountPrice: 6600,
        moq: 30,
        stock: 180,
        shippingDays: 4,
        country: "India",
        city: "Hyderabad",
        responseRate: "95%",
        responseTime: "Within 1 hour",
        gstVerified: true,
        trustScore: "85%",
        yearsInBusiness: 12,
        completedOrders: 675,
        totalProducts: 275,
        mobile: "+91 98765 40402",
      },
      {
        id: "s4-403",
        name: "BatteryMart",
        image: "https://placehold.co/300x300/fef08a/854d0e?text=BatteryMart",
        verified: true,
        rating: 4.1,
        reviews: 142,
        price: 6650,
        discountPrice: 6450,
        moq: 20,
        stock: 110,
        shippingDays: 6,
        country: "India",
        city: "Chennai",
        responseRate: "94%",
        responseTime: "Within 1.5 hours",
        gstVerified: true,
        trustScore: "82%",
        yearsInBusiness: 8,
        completedOrders: 520,
        totalProducts: 190,
        mobile: "+91 98765 40403",
      },
    ],
  },
  {
    id: "p5",
    name: "Industrial Grade Copper Wire (10 AWG)",
    category: "Raw Materials",
    image: "https://placehold.co/400x300/fcd34d/92400e?text=Copper+Wire",
    description:
      "High-purity copper wire for electrical and industrial applications.",
    suppliers: [
      {
        id: "s5-501",
        name: "MetalEx India",
        image: "https://placehold.co/300x300/fcd34d/92400e?text=MetalEx+India",
        verified: true,
        rating: 4.7,
        reviews: 210,
        price: 890,
        discountPrice: 845,
        moq: 200,
        stock: 460,
        shippingDays: 3,
        country: "India",
        city: "Mumbai",
        responseRate: "97%",
        responseTime: "Within 1 hour",
        gstVerified: true,
        trustScore: "88%",
        yearsInBusiness: 11,
        completedOrders: 720,
        totalProducts: 380,
        mobile: "+91 98765 50501",
      },
      {
        id: "s5-502",
        name: "Copperline Traders",
        image: "https://placehold.co/300x300/fcd34d/92400e?text=Copperline",
        verified: true,
        rating: 4.5,
        reviews: 162,
        price: 880,
        discountPrice: 840,
        moq: 250,
        stock: 560,
        shippingDays: 4,
        country: "India",
        city: "Vadodara",
        responseRate: "96%",
        responseTime: "Within 2 hours",
        gstVerified: true,
        trustScore: "86%",
        yearsInBusiness: 9,
        completedOrders: 580,
        totalProducts: 300,
        mobile: "+91 98765 50502",
      },
      {
        id: "s5-503",
        name: "MetalWorks Supply",
        image: "https://placehold.co/300x300/fcd34d/92400e?text=MetalWorks",
        verified: false,
        rating: 4.2,
        reviews: 108,
        price: 865,
        discountPrice: 820,
        moq: 300,
        stock: 380,
        shippingDays: 5,
        country: "India",
        city: "Ahmedabad",
        responseRate: "92%",
        responseTime: "Within 2 hours",
        gstVerified: false,
        trustScore: "80%",
        yearsInBusiness: 7,
        completedOrders: 440,
        totalProducts: 220,
        mobile: "+91 98765 50503",
      },
    ],
  },
  {
    id: "p6",
    name: "Polypropylene Granules (PP)",
    category: "Raw Materials",
    image: "https://placehold.co/400x300/c7d2fe/4338ca?text=PP+Granules",
    description:
      "Injection molding grade polypropylene granules for plastics manufacturing.",
    suppliers: [
      {
        id: "s6-601",
        name: "PlastWorld Corp",
        image: "https://placehold.co/300x300/c7d2fe/4338ca?text=PlastWorld",
        verified: true,
        rating: 4.6,
        reviews: 164,
        price: 92,
        discountPrice: 87,
        moq: 500,
        stock: 1820,
        shippingDays: 7,
        country: "India",
        city: "Vadodara",
        responseRate: "96%",
        responseTime: "Within 90 minutes",
        gstVerified: true,
        trustScore: "88%",
        yearsInBusiness: 13,
        completedOrders: 810,
        totalProducts: 470,
        mobile: "+91 98765 60601",
      },
      {
        id: "s6-602",
        name: "PolyMates",
        image: "https://placehold.co/300x300/c7d2fe/4338ca?text=PolyMates",
        verified: true,
        rating: 4.3,
        reviews: 138,
        price: 89,
        discountPrice: 85,
        moq: 600,
        stock: 940,
        shippingDays: 6,
        country: "India",
        city: "Vadodara",
        responseRate: "94%",
        responseTime: "Within 2 hours",
        gstVerified: true,
        trustScore: "85%",
        yearsInBusiness: 10,
        completedOrders: 620,
        totalProducts: 330,
        mobile: "+91 98765 60602",
      },
      {
        id: "s6-603",
        name: "ResinHub",
        image: "https://placehold.co/300x300/c7d2fe/4338ca?text=ResinHub",
        verified: false,
        rating: 4.4,
        reviews: 145,
        price: 90,
        discountPrice: 86,
        moq: 450,
        stock: 1330,
        shippingDays: 5,
        country: "India",
        city: "Mumbai",
        responseRate: "93%",
        responseTime: "Within 1 hour",
        gstVerified: false,
        trustScore: "82%",
        yearsInBusiness: 8,
        completedOrders: 590,
        totalProducts: 260,
        mobile: "+91 98765 60603",
      },
    ],
  },
  {
    id: "p7",
    name: "Stainless Steel Hex Bolts M12 x 50mm",
    category: "Hardware",
    image: "https://placehold.co/400x300/e5e7eb/374151?text=Hex+Bolts",
    description:
      "Precision stainless steel bolts for heavy-duty industrial assemblies.",
    suppliers: [
      {
        id: "s7-701",
        name: "Precision Fasteners",
        image:
          "https://placehold.co/300x300/e5e7eb/374151?text=Precision+Fasteners",
        verified: true,
        rating: 4.9,
        reviews: 418,
        price: 6.5,
        discountPrice: 5.8,
        moq: 1000,
        stock: 5600,
        shippingDays: 4,
        country: "India",
        city: "Coimbatore",
        responseRate: "99%",
        responseTime: "Within 30 minutes",
        gstVerified: true,
        trustScore: "92%",
        yearsInBusiness: 16,
        completedOrders: 1280,
        totalProducts: 920,
        mobile: "+91 98765 70701",
      },
      {
        id: "s7-702",
        name: "ForgeFix",
        image: "https://placehold.co/300x300/e5e7eb/374151?text=ForgeFix",
        verified: true,
        rating: 4.7,
        reviews: 298,
        price: 6.3,
        discountPrice: 5.6,
        moq: 1200,
        stock: 4800,
        shippingDays: 5,
        country: "India",
        city: "Coimbatore",
        responseRate: "97%",
        responseTime: "Within 1 hour",
        gstVerified: true,
        trustScore: "89%",
        yearsInBusiness: 14,
        completedOrders: 1050,
        totalProducts: 760,
        mobile: "+91 98765 70702",
      },
      {
        id: "s7-703",
        name: "BoltMasters",
        image: "https://placehold.co/300x300/e5e7eb/374151?text=BoltMasters",
        verified: false,
        rating: 4.4,
        reviews: 210,
        price: 6.2,
        discountPrice: 5.5,
        moq: 1300,
        stock: 4200,
        shippingDays: 6,
        country: "India",
        city: "Pune",
        responseRate: "93%",
        responseTime: "Within 2 hours",
        gstVerified: false,
        trustScore: "83%",
        yearsInBusiness: 7,
        completedOrders: 740,
        totalProducts: 530,
        mobile: "+91 98765 70703",
      },
    ],
  },
  {
    id: "p8",
    name: "Ball Bearings 6205-2RS",
    category: "Hardware",
    image: "https://placehold.co/400x300/d1d5db/111827?text=Bearings",
    description:
      "Durable double-sealed ball bearings for motors and conveyor systems.",
    suppliers: [
      {
        id: "s8-801",
        name: "SKF Bearing House",
        image:
          "https://placehold.co/300x300/d1d5db/111827?text=SKF+Bearing+House",
        verified: true,
        rating: 4.8,
        reviews: 402,
        price: 145,
        discountPrice: 132,
        moq: 250,
        stock: 400,
        shippingDays: 5,
        country: "India",
        city: "Delhi",
        responseRate: "96%",
        responseTime: "Within 1 hour",
        gstVerified: true,
        trustScore: "89%",
        yearsInBusiness: 20,
        completedOrders: 1450,
        totalProducts: 780,
        mobile: "+91 98765 80801",
      },
      {
        id: "s8-802",
        name: "BearingPlus",
        image: "https://placehold.co/300x300/d1d5db/111827?text=BearingPlus",
        verified: true,
        rating: 4.6,
        reviews: 290,
        price: 138,
        discountPrice: 128,
        moq: 280,
        stock: 520,
        shippingDays: 6,
        country: "India",
        city: "Mumbai",
        responseRate: "94%",
        responseTime: "Within 2 hours",
        gstVerified: true,
        trustScore: "87%",
        yearsInBusiness: 12,
        completedOrders: 960,
        totalProducts: 620,
        mobile: "+91 98765 80802",
      },
      {
        id: "s8-803",
        name: "MotionTech",
        image: "https://placehold.co/300x300/d1d5db/111827?text=MotionTech",
        verified: false,
        rating: 4.5,
        reviews: 215,
        price: 142,
        discountPrice: 133,
        moq: 260,
        stock: 360,
        shippingDays: 4,
        country: "India",
        city: "Bengaluru",
        responseRate: "92%",
        responseTime: "Within 2 hours",
        gstVerified: false,
        trustScore: "82%",
        yearsInBusiness: 9,
        completedOrders: 680,
        totalProducts: 410,
        mobile: "+91 98765 80803",
      },
    ],
  },
  {
    id: "p9",
    name: "Organic Cotton Yarn (Ne 30/1)",
    category: "Textiles",
    image: "https://placehold.co/400x300/f3f4f6/374151?text=Cotton+Yarn",
    description:
      "GOTS-certified organic cotton yarn for premium textile manufacturing.",
    suppliers: [
      {
        id: "s9-901",
        name: "GreenThread Textiles",
        image: "https://placehold.co/300x300/f3f4f6/374151?text=GreenThread",
        verified: false,
        rating: 4.3,
        reviews: 74,
        price: 340,
        discountPrice: 315,
        moq: 150,
        stock: 320,
        shippingDays: 7,
        country: "India",
        city: "Tiruppur",
        responseRate: "91%",
        responseTime: "Within 3 hours",
        gstVerified: false,
        trustScore: "80%",
        yearsInBusiness: 10,
        completedOrders: 420,
        totalProducts: 260,
        mobile: "+91 98765 90901",
      },
      {
        id: "s9-902",
        name: "EcoFiber Co",
        image: "https://placehold.co/300x300/f3f4f6/374151?text=EcoFiber+Co",
        verified: true,
        rating: 4.5,
        reviews: 102,
        price: 330,
        discountPrice: 310,
        moq: 180,
        stock: 240,
        shippingDays: 6,
        country: "India",
        city: "Coimbatore",
        responseRate: "95%",
        responseTime: "Within 2 hours",
        gstVerified: true,
        trustScore: "85%",
        yearsInBusiness: 12,
        completedOrders: 520,
        totalProducts: 310,
        mobile: "+91 98765 90902",
      },
      {
        id: "s9-903",
        name: "OrganicWeave",
        image: "https://placehold.co/300x300/f3f4f6/374151?text=OrganicWeave",
        verified: true,
        rating: 4.6,
        reviews: 128,
        price: 345,
        discountPrice: 322,
        moq: 140,
        stock: 180,
        shippingDays: 5,
        country: "India",
        city: "Tiruppur",
        responseRate: "97%",
        responseTime: "Within 1 hour",
        gstVerified: true,
        trustScore: "88%",
        yearsInBusiness: 14,
        completedOrders: 650,
        totalProducts: 380,
        mobile: "+91 98765 90903",
      },
    ],
  },
  {
    id: "p10",
    name: "Sulphuric Acid 98% (Industrial)",
    category: "Chemicals",
    image: "https://placehold.co/400x300/fecaca/991b1b?text=Sulphuric+Acid",
    description: "Technical grade sulphuric acid for industrial applications.",
    suppliers: [
      {
        id: "s10-1001",
        name: "ChemCore Industries",
        image: "https://placehold.co/300x300/fecaca/991b1b?text=ChemCore",
        verified: true,
        rating: 4.1,
        reviews: 56,
        price: 18.5,
        discountPrice: 17.2,
        moq: 1000,
        stock: 4200,
        shippingDays: 8,
        country: "India",
        city: "Vapi",
        responseRate: "94%",
        responseTime: "Within 2 hours",
        gstVerified: true,
        trustScore: "82%",
        yearsInBusiness: 18,
        completedOrders: 980,
        totalProducts: 420,
        mobile: "+91 98765 10001",
      },
      {
        id: "s10-1002",
        name: "AcidPro Supplies",
        image: "https://placehold.co/300x300/fecaca/991b1b?text=AcidPro",
        verified: true,
        rating: 4.3,
        reviews: 75,
        price: 18.8,
        discountPrice: 17.5,
        moq: 1200,
        stock: 3600,
        shippingDays: 7,
        country: "India",
        city: "Vapi",
        responseRate: "96%",
        responseTime: "Within 1 hour",
        gstVerified: true,
        trustScore: "85%",
        yearsInBusiness: 12,
        completedOrders: 740,
        totalProducts: 310,
        mobile: "+91 98765 10002",
      },
      {
        id: "s10-1003",
        name: "Industrial Chemicals Co",
        image: "https://placehold.co/300x300/fecaca/991b1b?text=IndChem+Co",
        verified: false,
        rating: 4.0,
        reviews: 48,
        price: 18.2,
        discountPrice: 17.1,
        moq: 900,
        stock: 4100,
        shippingDays: 9,
        country: "India",
        city: "Vadodara",
        responseRate: "92%",
        responseTime: "Within 3 hours",
        gstVerified: false,
        trustScore: "79%",
        yearsInBusiness: 8,
        completedOrders: 550,
        totalProducts: 250,
        mobile: "+91 98765 10003",
      },
    ],
  },
];

export default mockProducts;
